//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp_Telecom_Neva_Svyaz_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdressSubscriber
    {
        public int idAdressSubscriber { get; set; }
        public string Code { get; set; }
        public string Region { get; set; }
        public string Prefix { get; set; }
        public string House { get; set; }
    }
}
