//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp_Telecom_Neva_Svyaz_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectingTheService
    {
        public int IDOfTheConnectedService { get; set; }
        public int IDServices { get; set; }
        public int SubscribersID { get; set; }
        public Nullable<System.DateTime> ConnectionDate { get; set; }
    
        public virtual Contracts Contracts { get; set; }
        public virtual Servise Servise { get; set; }
    }
}
