//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp_Telecom_Neva_Svyaz_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainService
    {
        public int CRMID { get; set; }
        public string NumberCRM { get; set; }
        public System.DateTime DateCreation { get; set; }
        public int SubscriberID { get; set; }
        public int ServicesID { get; set; }
        public int ServiceTypeID { get; set; }
        public int ServiceStatusID { get; set; }
        public int ProblemTypeID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public Nullable<int> TypeOfServiceID { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Servise Servise { get; set; }
        public virtual Status Status { get; set; }
        public virtual TypeOfService TypeOfService { get; set; }
        public virtual TypeProblems TypeProblems { get; set; }
        public virtual TypesServices TypesServices { get; set; }
    }
}
