//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp_Telecom_Neva_Svyaz_2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesModel1 : DbContext
    {
        public EntitiesModel1()
            : base("name=EntitiesModel1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<ConnectingTheService> ConnectingTheService { get; set; }
        public virtual DbSet<Contracts> Contracts { get; set; }
        public virtual DbSet<Emploe> Emploe { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<InstallationEquipment> InstallationEquipment { get; set; }
        public virtual DbSet<KindsAndTypesService> KindsAndTypesService { get; set; }
        public virtual DbSet<MACAdress> MACAdress { get; set; }
        public virtual DbSet<MainService> MainService { get; set; }
        public virtual DbSet<Reasons> Reasons { get; set; }
        public virtual DbSet<Rols> Rols { get; set; }
        public virtual DbSet<SerialNumbers> SerialNumbers { get; set; }
        public virtual DbSet<Servise> Servise { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeEquipments> TypeEquipments { get; set; }
        public virtual DbSet<TypeOfService> TypeOfService { get; set; }
        public virtual DbSet<TypeProblems> TypeProblems { get; set; }
        public virtual DbSet<TypesOfContracts> TypesOfContracts { get; set; }
        public virtual DbSet<TypesServices> TypesServices { get; set; }
    }
}
