//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp_Telecom_Neva_Svyaz_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscriber
    {
        public int idSubscriber { get; set; }
        public string NumberSubscriber { get; set; }
        public string Surname { get; set; }
        public string FirstName { get; set; }
        public string Patronymic { get; set; }
        public int idGender { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string RegistrationAdress { get; set; }
        public string Number { get; set; }
        public string Passport { get; set; }
        public int idDivisionCode { get; set; }
        public int idIssued { get; set; }
        public System.DateTime IssuedDate { get; set; }
        public string ContractNumber { get; set; }
        public System.DateTime ConclusionDate { get; set; }
        public int idContractType { get; set; }
        public Nullable<int> idReasonTerminate { get; set; }
        public Nullable<System.DateTime> TerminateDate { get; set; }
        public string PersonalAccaunt { get; set; }
        public System.DateTime RentDate { get; set; }
        public int idSerialNumber { get; set; }
    }
}
