//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp_Telecom_Neva_Svyaz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public int idArea { get; set; }
        public string AreaName { get; set; }
        public string Sqare { get; set; }
        public int Population { get; set; }
        public int CountMetro { get; set; }
        public int idTypeBinding { get; set; }
    
        public virtual TypeBilding TypeBilding { get; set; }
    }
}
